apiVersion: v2
type: application
name: hephaestus
version: 0.7.2
appVersion: "latest"
kubeVersion: ">= 1.19.0-0"
description: Kubernetes operator that builds OCI images using buildkit.
home: https://github.com/dominodatalab/hephaestus
sources:
  - https://github.com/dominodatalab/hephaestus
  - https://github.com/moby/buildkit
maintainers:
  - name: Sonny Garcia
    email: sonny.garcia@dominodatalab.com
dependencies:
  - name: common
    version: 1.16.0
    repository: https://charts.bitnami.com/bitnami
