apiVersion: v2
type: application
name: hephaestus
version: 0.0.0
appVersion: "latest"
kubeVersion: ">= 1.16.0-0"
description: Kubernetes operator that builds OCI images using buildkit.
home: https://github.com/dominodatalab/hephaestus
maintainers:
  - name: Sonny Garcia
    email: sonny.garcia@dominodatalab.com
dependencies:
  - name: common
    version: 1.10.3
    repository: https://charts.bitnami.com/bitnami
